# Generated by Django 3.1.1 on 2021-02-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0003_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
